#!/bin/bash
set -e

echo " Generating documentation..."
echo ""

# Navigate to project root
cd "$(dirname "$0")/.."

# Extract version from Cargo.toml
VERSION=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
echo " Library Version: $VERSION"
echo ""

# Create docs directory
mkdir -p docs

# ============================================================================
# Rust Documentation
# ============================================================================
echo "════════════════════════════════════════════════════════════"
echo "Generating API Documentation"
echo "════════════════════════════════════════════════════════════"
echo ""

if command -v cargo &> /dev/null; then
    echo "Running cargo doc..."

    # Generate documentation with all features
    cargo doc --no-deps --all-features --target-dir ./target/doc-build

    # Copy to docs/lib
    echo " Copying docs to docs/lib..."
    rm -rf docs/lib
    mkdir -p docs/lib
    cp -r target/doc-build/doc/* docs/lib/

    # Create index redirect
    cat > docs/lib/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="refresh" content="0; url=rust_multiplatform_template_lib/index.html">
    <title>Redirecting...</title>
</head>
<body>
    <p>Redirecting to <a href="rust_multiplatform_template_lib/index.html">documentation</a>...</p>
</body>
</html>
EOF

    echo ""
    echo "[SUCCESS] Documentation generated successfully!"
    echo ""
    echo " Documentation Location:"
    echo "   docs/lib/index.html"
    echo ""
    echo " To view locally:"
    echo "   open docs/lib/index.html"
    echo ""
    echo "   Or start a local server:"
    echo "   cd docs && python3 -m http.server 8000"
    echo "   Then open: http://localhost:8000/lib/"
    echo ""
    echo " To publish to GitHub Pages:"
    echo "   git add docs/"
    echo "   git commit -m 'Update documentation'"
    echo "   git push"
    echo ""
    echo "  Note: Swift and Kotlin bindings are auto-generated by UniFFI."
    echo "   This Rust documentation is the source of truth for the API."
    echo ""
    exit 0
else
    echo "[FAILED] cargo not found - cannot generate documentation"
    echo ""
    echo "Please install Rust from https://rustup.rs/"
    echo ""
    exit 1
fi
